### ISSUE TITLE
Space as leader key in insert mode

### ISSUE THREAD

**Issue by lazywei** [junegunn/dotfiles#2]
Hi,

This is not really an issue. I'm just wondering, when using `<space>` as leader key, it seems to cause delay in insert mode if you tries to enter "space". The reason is that vim will wait for next key to check if you want to trigger a `<leader>somthing` or just a normal space.
How do you resolve this? Is it possible to disable leader key in the insert mode?

Thanks :+1:

**Comment by junegunn** [comment]
> it seems to cause delay in insert mode if you tries to enter "space"

It doesn't if you don't have insert-mode mappings that start with space. `:imap <leader>` to see those mappings and eradicate them.

**Comment by lazywei** [comment]
You are right! Sorry for bothering. Thanks a lot :smile:
