### ISSUE TITLE
FZF preview window

### ISSUE THREAD

**Issue by jrock2004** [junegunn/dotfiles#4]
Was seeing a talk that you have setup somehow to when using FZF you can get a preview of the file that you are highlighting. How can I do this?

**Comment by junegunn** [comment]
- `man fzf`
- https://junegunn.kr/2016/07/fzf-git/
- https://github.com/junegunn/fzf.vim#advanced-customization

**Comment by zoechi** [comment]
Seems with some suggested settings (`FZF_DEFAULT_OPTS`) it is configured to show the preview only after pressing <kbd>F2</kbd>
