### ISSUE TITLE
v() suggestion

### ISSUE THREAD

**Issue by dthng** [junegunn/dotfiles#9]
Hello!

it seems v() function in bashrc does not play well with nvim, i did a small change so that the function now works with nvim too 

```
# Vim integration
# v - open files in ~/.viminfo or v:oldfiles in case of nvim, since nvim uses
# shada file, which cannot be easily read
v() {
  local OLDFILES="$HOME/.tmpoldfiles.txt"
  > $OLDFILES
  if [ "${EDITOR}" = "nvim" ]; then
      $EDITOR -es -c"redir! > ${OLDFILES} | echo v:oldfiles | redir END | qa"
      sed -i -e's/^\[//' -e's/\]$//' -e's/, /\n/g' ${OLDFILES}
      sed -i -e"s/^'//" -e"s/'$//" ${OLDFILES}
  fi

  local files
  files=$({ cat ${OLDFILES} ; grep '^>' ~/.viminfo | cut -c3- ; } |
          while read line; do
            [ -f "${line/\~/$HOME}" ] && echo "$line"
          done | fzf -d -m -q "$*" -1) && ${EDITOR:-vim} ${files//\~/$HOME}
}
```

I hope that will be useful!

Cheer
Thanh

**Comment by junegunn** [comment]
Nice, thanks.

I just realized that I don't really use this function. I've been using neovim for years and that I haven't realized that `v()` gives me the wrong result tells. Since I use fzf.vim, I can easily replace this with `vim +History` or `nvim +History`.
